# Generated by Django 3.2.4 on 2021-07-31 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservations',
            name='place',
            field=models.CharField(choices=[('LUX-1', 'LUX-1'), ('LUX-2', 'LUX-2'), ('LUX-3', 'LUX-3'), ('LUX-4', 'LUX-4'), ('LUX-5', 'LUX-5'), ('Ordinary places-1', 'Ordinary places-1'), ('Ordinary places-2', 'Ordinary places-2'), ('Ordinary places-3', 'Ordinary places-3'), ('Ordinary places-4', 'Ordinary places-4'), ('Ordinary places-5', 'Ordinary places-5')], default='1', max_length=20),
        ),
    ]
