# Generated by Django 3.2.4 on 2021-08-03 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_reservations_place'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Menu_category',
        ),
    ]
