# Generated by Django 3.2.4 on 2021-08-03 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210803_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
