# Generated by Django 3.2.4 on 2021-08-03 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_table_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='table_category',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
