# Generated by Django 3.2.4 on 2021-08-03 12:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20210803_1656'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table_category',
            name='t_id',
        ),
        migrations.AddField(
            model_name='order',
            name='data',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='table',
            name='price',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='price',
            field=models.FloatField(),
        ),
    ]
